### ISSUE TITLE
Start TLS support

### ISSUE THREAD

**Issue by igoratencompass** [tiagoapimenta/nginx-ldap-auth#1]
Hi,
Thanks for this work. Is LDAP with STARTTLS supported?

**Comment by igoratencompass** [comment]
That's great maybe mentioning that in the readme can be useful. Plus maybe an example how would this:

```
servers:
    - ldaps://ldap1.example.com:636
    - ldaps://ldap2.example.com:636
    - ldaps://ldap3.example.com:636
```
look in that case. Is it like:

```
servers:
    - ldap://ldap1.example.com:587
    - ldap://ldap2.example.com:587
```
maybe?

**Comment by tiagoapimenta** [comment]
Yes, it should work, please tell me if you succeed, I will improve the docs.

**Comment by tiagoapimenta** [comment]
I have updated the docs and fixed the Secret issue, I was using ConfigMap before, it is slightly different

**Comment by igoratencompass** [comment]
Thanks for the update. I just created a PR to add RBAC support, please have a look.

**Comment by tiagoapimenta** [comment]
Sure, next version I'm planning to allow header based rules to match user and groups, by now it is all.
