### ISSUE TITLE
Escape characters

### ISSUE THREAD

**Issue by dignajar** [tiagoapimenta/nginx-ldap-auth#14]
Hi,
we have a problem with some characters in our AD, for example in the groups we have `member: CN=Username\,Name` something like that and the problem is the `\` and we got this error log `2019/05/13 14:04:45 Could not validate user <redacted>: LDAP Result Code 201 "Filter Compile Error": ldap: invalid characters for escape in filter`.

Maybe would be good to escape these characters (https://github.com/hashicorp/vault/issues/1030#issuecomment-180729432) using the function `ldap.EscapeFilter`, I think the problem is on the `id` variable, but this is because of my groups.

Regards

**Comment by tiagoapimenta** [comment]
Thanks to @gered
