### ISSUE TITLE
Basic auth stop to work after upgrading to kubernetes 1.16

### ISSUE THREAD

**Issue by massimeddu** [tiagoapimenta/nginx-ldap-auth#17]
After upgrading to kubernetes 1.16 the system stopped to prompt the basic auth and automatically open the downstream service.

It looks like the nginx-ingress is totally ignoring the nginx.ingress.kubernetes.io/auth-url annotation.

**Comment by tiagoapimenta** [comment]
Have you tried to follow [this guide](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)? It seems Ingress **extensions/v1beta1** have been migrated to **networking.k8s.io/v1beta1**, please, validate the solution and feed me back.

**Comment by massimeddu** [comment]
Hi @tiagoapimenta thanks for the suggestion. I've updated the api version to networking.k8s.io/v1beta1 but unfortunately it didn't solve the issue.

**Comment by tiagoapimenta** [comment]
I have updated to `1.17` and tested, it seems ok for me, try with new [yaml](https://github.com/tiagoapimenta/nginx-ldap-auth/blob/master/k8s.yaml) please.
