### ISSUE TITLE
LDAP connection errors seem not to be recovered

### ISSUE THREAD

**Issue by vcariven** [tiagoapimenta/nginx-ldap-auth#4]
Hello,

If LDAP connection is temporary lost, nginx-ldap-auth seems unable to recover.

Steps to reproduce:
* Start nginx-ldap-auth
```
Loaded config "/etc/nginx-ldap-auth/config.yaml".
Serving...
```
* Stop LDAP endpoint
* Try to authenticate with a user XXXXXX (this should fail as the LDAP endpoint is stopped)
```
2018/11/12 08:53:44 Could not validade user XXXXXX: LDAP Result Code 200 "Network Error": ldap: connection closed
```
* Restart the LDAP endpoint
* It seems that we are not able to login again with any user

I don't how to recover the ldap connection...

Regards,

Keep up the good job !

**Comment by tiagoapimenta** [comment]
@vcariven please, try with v1.0.3 now
