### ISSUE TITLE
requiredGroups never checked

### ISSUE THREAD

**Issue by cosimomeli** [tiagoapimenta/nginx-ldap-auth#6]
Hi,
seems like in the validate function at line 57
`if ok || p.required == nil || len(p.required) == 0 {
		return err == nil, nil
}`

that "ok ||" causes groups check to be always skipped.

**Comment by tiagoapimenta** [comment]
You're right, it is not ok instead.

**Comment by tiagoapimenta** [comment]
### API error
ok = false
err = non-nil
### User pass valid
ok = true
err = nil
### User pass invalid
ok = true
err = non-nil
## Conclusion
`ok` is checking the API errors, and `err` is the result of the password validation
