### ISSUE TITLE
enhancement: selectively LDAP authentication based on label or taint

### ISSUE THREAD

**Issue by frederic-loui** [tiagoapimenta/nginx-ldap-auth#7]
Hi, this container is working perfectly ! Not sure if this is possible or easy, I was asked to add application that can handle authentication itself. So no need to use LDAP. One solution is to use another nginx-ingress. But I was just wondering if it was possible to onlt use LDAP AUTHENTICATION when label=nginx-ldap-auth in the service definition is et for example ? Oherwise, it works like a charm. Thanks/Frederic

**Comment by tiagoapimenta** [comment]
I don't know if I get it, but you can have several application managed by ingress, each one with theirs independent ingress configuration, you can determine the ones with and without authentication based on the annotation `nginx.ingress.kubernetes.io/auth-url`, the ones who has it will require authentication, the ones without won't, is that what you are looking for?

**Comment by frederic-loui** [comment]
Well, just keep your current way of activating the module.
But upon label value set at the service level, let's say:
NGINX_LDAP_AUTH=true activate ldaps auth via the module ?

**Comment by tiagoapimenta** [comment]
I don't believe this application could afford such a behaviour on kubernetes, maybe a kubernetes specific  plugin, I don't know, but you see it is not a thing could be achieved by a running application.
